target 'WithAttend' do
use_frameworks!
pod 'Meteor'
pod 'SwiftDDP', '~> 0.3.4'
pod 'Fabric'
pod 'Crashlytics'
pod 'Firebase/Core'
pod 'Firebase/Messaging'
pod 'Firebase/Auth'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
